language: ruby
rvm:
- 2.5
before_install:
- gem update --system
- gem install bundler
install:
- bundle install
cache:
- bundler
script:
- bundle exec rspec
before_deploy:
- docker run -it --rm -v "$PWD":/var/task lambci/lambda:build-ruby2.5 bundle install
  --deployment
deploy:
- provider: lambda
  function_name: SubjectHeadingPoster-dev
  description: A service to listen to the Bib stream and post data for research bibs
    to the SHEP API
  region: us-east-1
  role: arn:aws:iam::224280085904:role/lambda_basic_execution
  runtime: ruby2.5
  timeout: 60
  module_name: app
  handler_name: handle_event
  environment_variables:
  - SHEP_API_BIBS_ENDPOINT=http://shep-api-new-development.us-east-1.elasticbeanstalk.com/api/v0.1/bibs/
  - PLATFORM_API_BASE_URL=https://dev-platform.nypl.org/api/v0.1/
  - NYPL_OAUTH_URL=https://isso.nypl.org/
  - NYPL_OAUTH_ID=AQECAHjqALewp8JBJNxIQvR4oY795dyG7INaGR1glMsTEgetggAAAHIwcAYJKoZIhvcNAQcGoGMwYQIBADBcBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDBYrzA0rotNRV+0dMAIBEIAvGeyPXEKVTIlR+vzIs5h/0ojU/3TH3R8HX3h3xHCZp76m7mVzyRDNyREPFwq45TI=
  - NYPL_OAUTH_SECRET=AQECAHjqALewp8JBJNxIQvR4oY795dyG7INaGR1glMsTEgetggAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzvLVLGEyP0EuIQC9YCARCAQ1AKv2geABsSFPvtI1JWX6YMbL348GLXhgK/dCrYs6aMQrufTjSlUi2ytOvbJpcSkPqDxHyfpjnfzBI7lGSVKP7D3mA=
  - NYPL_CORE_S3_BASE_URL=https://s3.amazonaws.com/nypl-core-objects-mapping-production/
  - LOG_LEVEL=debug
  access_key_id: "$AWS_ACCESS_KEY_ID_DEV"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEV"
  on:
    branch: dev
- provider: lambda
  function_name: SubjectHeadingPoster-qa
  description: A service to listen to the Bib stream and post data for research bibs
    to the SHEP API
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.5
  timeout: 60
  module_name: app
  handler_name: handle_event
  environment_variables:
  - SHEP_API_BIBS_ENDPOINT=http://subjectheadingexplorerpoc-qa-2.pchxmxsxky.us-east-1.elasticbeanstalk.com/api/v0.1/bibs/
  - PLATFORM_API_BASE_URL=https://qa-platform.nypl.org/api/v0.1/
  - NYPL_OAUTH_URL=https://isso.nypl.org/
  - NYPL_OAUTH_ID=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGswaQYJKoZIhvcNAQcGoFwwWgIBADBVBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAJNGpqeEeETCmeurQIBEIAoz+HbpFuGMH/84X9UVisMtsRCo5lIguWzG6PGCf3Q97JMk6Dvo+AZeQ==
  - NYPL_OAUTH_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwDTxUAqKkiCrdL90MCARCAQ8vxU5R+MEGRpWFPhktni6yfDNoecmxWlerXkaWk+ZUaPKdUlkTI1kDITaWnwf9VvR4N9XwGgKMLfWgM+sW72715eqc=
  - NYPL_CORE_S3_BASE_URL=https://s3.amazonaws.com/nypl-core-objects-mapping-production/
  - LOG_LEVEL=debug
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: qa
- provider: lambda
  function_name: SubjectHeadingPoster-prod
  description: A service to listen to the Bib stream and post data for research bibs
    to the SHEP API
  region: us-east-1
  role: arn:aws:iam::946183545209:role/lambda-full-access
  runtime: ruby2.5
  timeout: 60
  module_name: app
  handler_name: handle_event
  environment_variables:
  - SHEP_API_BIBS_ENDPOINT=http://subjectheadingexplorerpoc-production.us-east-1.elasticbeanstalk.com/api/v0.1/bibs/
  - PLATFORM_API_BASE_URL=https://platform.nypl.org/api/v0.1/
  - NYPL_OAUTH_URL=https://isso.nypl.org/
  - NYPL_OAUTH_ID=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGswaQYJKoZIhvcNAQcGoFwwWgIBADBVBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAJNGpqeEeETCmeurQIBEIAoz+HbpFuGMH/84X9UVisMtsRCo5lIguWzG6PGCf3Q97JMk6Dvo+AZeQ==
  - NYPL_OAUTH_SECRET=AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwDTxUAqKkiCrdL90MCARCAQ8vxU5R+MEGRpWFPhktni6yfDNoecmxWlerXkaWk+ZUaPKdUlkTI1kDITaWnwf9VvR4N9XwGgKMLfWgM+sW72715eqc=
  - NYPL_CORE_S3_BASE_URL=https://s3.amazonaws.com/nypl-core-objects-mapping-production/
  - LOG_LEVEL=info
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  on:
    branch: production
notifications:
  email:
    on_failure: always
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: Ct5SuTLx6ORRGWhuihI3AubsfGPIsmcMGGBtdpd57HTd3ZjC5XXXlseeYfWigvaNA3A9NT4LDxdJkcYCTpkpEXT7kCx5nalmfhTqgdxeIwr6S76lj2NsVedITc2EYeeDG/Y7D1Jb0ieX2iHdEIK0qPt2cIWlzladb0Xa9O10TsVNX58FacWs16N3/HtjytLpN3bXS+h1Wt3c0f/ts+u58rlH7fa+vmvDWuZilkW0OnS4h/fKITBvw3Hbl7PXmKIDiIk/O9zNJixLpV8RNGAAfUFYwJlgAkvqpeeNllzjjp/kfnI9DOKHW70tBvHOTEKdODmEbFskA0gIA8rfHkDTxQ8WMeryTC8fXIQtFLBOr4d1eXJo/Scf3qtydhsobMnxUw3tzfRDxlO0ItMutQGg+FWfnMEXK33iSOrL1RvBGwXw1ByVxXZZDxIkCCx6yyq81FD6qZYkzTYXFNF7vf6zZM2pGLuZso4c81nofaOiKI8s20/kC6GqTmdsES3zpK1nccFQaNfS75JinW++3WKxHXj08BWl1OuNM99houhc6PtnYMVqbnqnDrP9npvNDYuxR5bZ4fTNwD+h8FrMDILr1whva7g4gHFR+dZRZHiiv0DzjB7vjpb2umtxWC8triH9zQDgwp7KHz+x9Q9+0H155ba9YW0OnUIZfKU53dK9qmo=
  - secure: eIqsmKiSKe4MbHIrS4NlU0mWrQzSKTQjv/ezc/1EuHGG8occ5yOg/u4Z+Oars4aoE1jlRpY83keOAZGN/YyeD2Zi0sCBI9szR5t68dzoJy/D7PhtuBrH0ifZT2VMq4JAaZUwWDZKNN6RuQByeKPdNyHnSMnKWdYotoqbZ/kYvhCWCT9bhGdNVGrWWJGQjPoXoXcrk3ofko8M5JDnOBstb0FmnEK381wGRRroVuFVvyY5ZN/+sQsjvMbVt9XIWLTBBumC+smYoOKsbqJGx7KVSWP/vdAJNoqDXwlF7zCx2CLXsHbbOGU/ge2+KsHfZfAk8wH3tqfc5RC9aVKqTLC+60Mnw2MUV2P2O2UVyXs5L3i80yQ2keKEH4DuzYsGGc0Y/scdM5pWbll58yBBjBBOPfycxtsPU2R+55LF2SJPmUKmsLrbpNYtZuy71gIj9zw3nh9kABKmH8AFyTncTVwxyaQ6YuKRIe1tTf89egkapM/DqsBg/TC8MWzLRRjnRRw23rBcGfMn+8+Z1OEIhlUj6qmHYu2HajM/dAApGrNss4kzIUHY7v/sSHyJi7vgyrhFGSPLKAVcHK1kSii5M79NmLnPJe2vufjHGE9HCwWhqr6+31O1B47pOvPeYWjEjAS3DugEQyure5E2d4Zzlw0cde6eKZJ8nHEclt/MIXYVh6w=
  - secure: o8dkKFdP8ZD06M0DbLFSovCt2pnink6nI1Z9CT8OnI97k8H4VALup9caS4JMHsLuQcUJ79U2GgA4ot48wY28Wqc8iQ8T+X7D6FMXi4VVqpu2mld+MJAX+2pW0kdiyxJz3X+rEy6/p5EkmgfjY71OZ/1vSAcmDVVSOXk2narCPuUPYQpOz/jzzohrlPHYO4+iyVOwCZGcUHI2/2UjCNBrR9a3xGn2bRZUu4037snxB9e21Hq+qr22nSA++zzPZeWW2hH+s6kQsgp5Rr+t9rxnk7z7hwvB8PcxdzoB1u1I5akRfzjs1uG8hM+e29iZn2BK8cfxQUiMzw/CNefJdXIuK28y4Uhqiqt2HNBNC8D7r6gbz2n0higmGvgB6yQArLLVy1Pmk+T1+/E5aCbj39hEIaoTxCGFBD/eviFHeHYifaRPltgfLqtQMRz+cK4fffZtEw0QdnB3SuQVpb0M5bZOMc0knBK07Qvciw4KWuD+MKrSHf5WpoCM0GgyjylA5wbfysaR5lQo66mIcT8kwKsxEO8/T4qLvveC4w+ni/ihz8lrMwUZCfiD5ryUl/d6lCvL/XoJ5YN97ucj+msGI6zLLK2bRuNzxLE6+6rxZ7i3Al7bsgtCIK9golgkjNTTq6UeSeqjdP4JYPMCvUKaB/gjcCd+dup56SEwD8VymY4OTQQ=
  - secure: uN1A7/x7x2W19Qx1ukdXZjNzz/Ab8rzd1BMigGFaHyLeRK4ySBK4c5A7BxHN2pcDByzuqdvhyz6EoV99eIYHYopwWvUsN/UsK1A4M7ynaj5SOOX0VxfBQrft+J3wgMS27TJF3y5rZBoY1cbD8oEYAnm5z6FfCCKbqfY6+WGAkYctyx7u3631KmQk8HEGfdXP+/CEfG9lGSzg82x8qyUU4CLir52wa65cXm5fjdZ+YySldkQGoRSHEHWgccHK9+8p74XdMJaOzkr/0qYFgW7lFgxEtst0M/Yb0GumeQPDQv9T889ZybESfAYJF7LQFpsZirSkskL4lIOPsy1adkFnOgV9RgJaeMdDJ22hIffv3RRhzaJVGDx1CLvkm9o3wN3n9TEaFumi2tRzmXaLy7vbEf7aX4BWmSIaVP22TT3OgPkGlGTnpdCH/SgMiamYgNKVMiVsA2aG+iKdnPcWfeLlEj3+patd1gX+PBOuPrLkB8yPNHZywh5nJ/sheNuVFSKsEkC6BUYwcGERLMrS0oiY6x56qc9xvl/sW26Q4GNReR0Nbir8rzQHGwYTXqBItcGwlk3ou+BNNwjHYgcXJ8WYa3DTEqFCnf9RWv72CtBFUbEBvxov84T0xlHC+kCg4BY4YyqjLBJigaUxO50AuoS6LWWkwzeJu4YCd6m89xvkwqs=
  - secure: X1TcmTfSjdSe1db54pUOD8h2HYlwoZtxmN7ggB0NGaAx9w5UYUcq5erBahVMZ92Ac1WzUi3vHdMb3i0yBgTuBok2LGZuuf97zVkTvMUfrmbQtgX8O3frAWH1PbJWV9womLl+hGz8kGARlkcqrGUvp4kyQfiZ60QKRAfBf0/VAIubf52kvJdw9qGcFhOS6x4H0UqimWs9Q7PSyyhtbrWEbgFMe2c6qCd4QFmIf1cP/tpn6wVXJcUAFHZpIittfCGn0Gv9hau6IPZZ11TTbkOiV/ivwsXHLGc87xNmXTp/URSwxnqMmJlGEtgfZ6X1KJVDt8615uRUc872epPs7EgvPcqVxo2dlY4VJRkXvwpqcZsFm/OunsOo3X3gmS3jY8FkH0Q22WX88b3ALoqLT6n/DsmNMiusxVPxiAPFK5LtkB2tW/LW5CNYM8FFVd1ZYF6F5BqTijmO5VYu1QV/K9W3vmMg6ucQJu2ZA8bFre7vicJro0o/40xfpZVbmnQ0t3kBdecz3o9EXs+TF8DXmLS5jM4ttbFQbQ9kUD1KBsVsKTK3uL49v2/eHZMH1hIodloG9WEfUDUj3zDRm1A3TNFuojiN3DrAYGA+abFYhdyWhqrGC4DLzx9B7Pc6+AfoPe/U7xt3LOWcapfJiI+SN2ufZPgYNc7usdCU5dYTeeEueMg=
